# Generated by Django 2.1.15 on 2020-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='random_offset',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
